### PR TITLE
Added a beginner level program and also provided two fixes to issue #9

### PR DESCRIPTION
**Pull request by GenDelta**
This program takes a number as input from the user and checks whether the given number is an Armstrong number or not and gives an output accordingly. The definition of an Armstrong number and a suitable example of the same are mentioned in a multi-line comment at the start of the program.

### CODE REVIEW

**Comment by GenDelta** [comment]
Added a program to demonstrate the stack data structure. The program is executed mainly via a switch case block in the code.

**Comment by GenDelta** [comment]
I have added a program to demonstrate the Queue data structure. This program is executed using a switch case block inside a do-while loop all in the main() method.

**Comment by DcodeZw3** [comment]
try to commit in then specific issue dont send generic PRs

**Review by GenDelta — COMMENTED** [review]
#9

**Review by GenDelta — COMMENTED** [review]
#9

**Pull request closed without merging**
